/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.17
 * Generated at: 2019-04-06 15:32:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.eleves;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class _404_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "Les JSPs ne permettent que GET, POST ou HEAD. Jasper permet aussi OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Oups, quelque chose s'est mal passé</title>\r\n");
      out.write("<style>\r\n");
      out.write("@import url(https://fonts.googleapis.com/css?family=opensans:500);\r\n");
      out.write("body{\r\n");
      out.write("                background: #33cc99;\r\n");
      out.write("                color:#fff;\r\n");
      out.write("                font-family: 'Open Sans', sans-serif;\r\n");
      out.write("                max-height:700px;\r\n");
      out.write("                overflow: hidden;\r\n");
      out.write("            }\r\n");
      out.write("            .c{\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                display: block;\r\n");
      out.write("                position: relative;\r\n");
      out.write("                width:80%;\r\n");
      out.write("                margin:100px auto;\r\n");
      out.write("            }\r\n");
      out.write("            ._404{\r\n");
      out.write("                font-size: 220px;\r\n");
      out.write("                position: relative;\r\n");
      out.write("                display: inline-block;\r\n");
      out.write("                z-index: 2;\r\n");
      out.write("                height: 250px;\r\n");
      out.write("                letter-spacing: 15px;\r\n");
      out.write("            }\r\n");
      out.write("            ._1{\r\n");
      out.write("                text-align:center;\r\n");
      out.write("                display:block;\r\n");
      out.write("                position:relative;\r\n");
      out.write("                letter-spacing: 12px;\r\n");
      out.write("                font-size: 4em;\r\n");
      out.write("                line-height: 80%;\r\n");
      out.write("            }\r\n");
      out.write("            ._2{\r\n");
      out.write("                text-align:center;\r\n");
      out.write("                display:block;\r\n");
      out.write("                position: relative;\r\n");
      out.write("                font-size: 20px;\r\n");
      out.write("            }\r\n");
      out.write("            .text{\r\n");
      out.write("                font-size: 70px;\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                position: relative;\r\n");
      out.write("                display: inline-block;\r\n");
      out.write("                margin: 19px 0px 0px 0px;\r\n");
      out.write("                /* top: 256.301px; */\r\n");
      out.write("                z-index: 3;\r\n");
      out.write("                width: 100%;\r\n");
      out.write("                line-height: 1.2em;\r\n");
      out.write("                display: inline-block;\r\n");
      out.write("            }\r\n");
      out.write("           \r\n");
      out.write("\r\n");
      out.write("            .btn{\r\n");
      out.write("                background-color: rgb( 255, 255, 255 );\r\n");
      out.write("                position: relative;\r\n");
      out.write("                display: inline-block;\r\n");
      out.write("                width: 358px;\r\n");
      out.write("                padding: 5px;\r\n");
      out.write("                z-index: 5;\r\n");
      out.write("                font-size: 25px;\r\n");
      out.write("                margin:0 auto;\r\n");
      out.write("                color:#33cc99;\r\n");
      out.write("                text-decoration: none;\r\n");
      out.write("                margin-right: 10px\r\n");
      out.write("            }\r\n");
      out.write("            .right{\r\n");
      out.write("                float:right;\r\n");
      out.write("                width:60%;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            hr{\r\n");
      out.write("                padding: 0;\r\n");
      out.write("                border: none;\r\n");
      out.write("                border-top: 5px solid #fff;\r\n");
      out.write("                color: #fff;\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                margin: 0px auto;\r\n");
      out.write("                width: 420px;\r\n");
      out.write("                height:10px;\r\n");
      out.write("                z-index: -10;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            hr:after {\r\n");
      out.write("                content: \"\\2022\";\r\n");
      out.write("                display: inline-block;\r\n");
      out.write("                position: relative;\r\n");
      out.write("                top: -0.75em;\r\n");
      out.write("                font-size: 2em;\r\n");
      out.write("                padding: 0 0.2em;\r\n");
      out.write("                background: #33cc99;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .cloud {\r\n");
      out.write("                width: 350px; height: 120px;\r\n");
      out.write("\r\n");
      out.write("                background: #FFF;\r\n");
      out.write("                background: linear-gradient(top, #FFF 100%);\r\n");
      out.write("                background: -webkit-linear-gradient(top, #FFF 100%);\r\n");
      out.write("                background: -moz-linear-gradient(top, #FFF 100%);\r\n");
      out.write("                background: -ms-linear-gradient(top, #FFF 100%);\r\n");
      out.write("                background: -o-linear-gradient(top, #FFF 100%);\r\n");
      out.write("\r\n");
      out.write("                border-radius: 100px;\r\n");
      out.write("                -webkit-border-radius: 100px;\r\n");
      out.write("                -moz-border-radius: 100px;\r\n");
      out.write("\r\n");
      out.write("                position: absolute;\r\n");
      out.write("                margin: 120px auto 20px;\r\n");
      out.write("                z-index:-1;\r\n");
      out.write("                transition: ease 1s;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .cloud:after, .cloud:before {\r\n");
      out.write("                content: '';\r\n");
      out.write("                position: absolute;\r\n");
      out.write("                background: #FFF;\r\n");
      out.write("                z-index: -1\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .cloud:after {\r\n");
      out.write("                width: 100px; height: 100px;\r\n");
      out.write("                top: -50px; left: 50px;\r\n");
      out.write("\r\n");
      out.write("                border-radius: 100px;\r\n");
      out.write("                -webkit-border-radius: 100px;\r\n");
      out.write("                -moz-border-radius: 100px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .cloud:before {\r\n");
      out.write("                width: 180px; height: 180px;\r\n");
      out.write("                top: -90px; right: 50px;\r\n");
      out.write("\r\n");
      out.write("                border-radius: 200px;\r\n");
      out.write("                -webkit-border-radius: 200px;\r\n");
      out.write("                -moz-border-radius: 200px;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .x1 {\r\n");
      out.write("                top:-50px;\r\n");
      out.write("                left:100px;\r\n");
      out.write("                -webkit-transform: scale(0.3);\r\n");
      out.write("                -moz-transform: scale(0.3);\r\n");
      out.write("                transform: scale(0.3);\r\n");
      out.write("                opacity: 0.9;\r\n");
      out.write("                -webkit-animation: moveclouds 15s linear infinite;\r\n");
      out.write("                -moz-animation: moveclouds 15s linear infinite;\r\n");
      out.write("                -o-animation: moveclouds 15s linear infinite;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .x1_5{\r\n");
      out.write("                top:-80px;\r\n");
      out.write("                left:250px;\r\n");
      out.write("                -webkit-transform: scale(0.3);\r\n");
      out.write("                -moz-transform: scale(0.3);\r\n");
      out.write("                transform: scale(0.3);\r\n");
      out.write("                -webkit-animation: moveclouds 17s linear infinite;\r\n");
      out.write("                -moz-animation: moveclouds 17s linear infinite;\r\n");
      out.write("                -o-animation: moveclouds 17s linear infinite; \r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .x2 {\r\n");
      out.write("                left: 250px;\r\n");
      out.write("                top:30px;\r\n");
      out.write("                -webkit-transform: scale(0.6);\r\n");
      out.write("                -moz-transform: scale(0.6);\r\n");
      out.write("                transform: scale(0.6);\r\n");
      out.write("                opacity: 0.6; \r\n");
      out.write("                -webkit-animation: moveclouds 25s linear infinite;\r\n");
      out.write("                -moz-animation: moveclouds 25s linear infinite;\r\n");
      out.write("                -o-animation: moveclouds 25s linear infinite;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .x3 {\r\n");
      out.write("                left: 250px; bottom: -70px;\r\n");
      out.write("\r\n");
      out.write("                -webkit-transform: scale(0.6);\r\n");
      out.write("                -moz-transform: scale(0.6);\r\n");
      out.write("                transform: scale(0.6);\r\n");
      out.write("                opacity: 0.8; \r\n");
      out.write("\r\n");
      out.write("                -webkit-animation: moveclouds 25s linear infinite;\r\n");
      out.write("                -moz-animation: moveclouds 25s linear infinite;\r\n");
      out.write("                -o-animation: moveclouds 25s linear infinite;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .x4 {\r\n");
      out.write("                left: 470px; botttom: 20px;\r\n");
      out.write("\r\n");
      out.write("                -webkit-transform: scale(0.75);\r\n");
      out.write("                -moz-transform: scale(0.75);\r\n");
      out.write("                transform: scale(0.75);\r\n");
      out.write("                opacity: 0.75;\r\n");
      out.write("\r\n");
      out.write("                -webkit-animation: moveclouds 18s linear infinite;\r\n");
      out.write("                -moz-animation: moveclouds 18s linear infinite;\r\n");
      out.write("                -o-animation: moveclouds 18s linear infinite;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .x5 {\r\n");
      out.write("                left: 200px; top: 300px;\r\n");
      out.write("\r\n");
      out.write("                -webkit-transform: scale(0.5);\r\n");
      out.write("                -moz-transform: scale(0.5);\r\n");
      out.write("                transform: scale(0.5);\r\n");
      out.write("                opacity: 0.8; \r\n");
      out.write("\r\n");
      out.write("                -webkit-animation: moveclouds 20s linear infinite;\r\n");
      out.write("                -moz-animation: moveclouds 20s linear infinite;\r\n");
      out.write("                -o-animation: moveclouds 20s linear infinite;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            @-webkit-keyframes moveclouds {\r\n");
      out.write("                0% {margin-left: 1000px;}\r\n");
      out.write("                100% {margin-left: -1000px;}\r\n");
      out.write("            }\r\n");
      out.write("            @-moz-keyframes moveclouds {\r\n");
      out.write("                0% {margin-left: 1000px;}\r\n");
      out.write("                100% {margin-left: -1000px;}\r\n");
      out.write("            }\r\n");
      out.write("            @-o-keyframes moveclouds {\r\n");
      out.write("                0% {margin-left: 1000px;}\r\n");
      out.write("                100% {margin-left: -1000px;}\r\n");
      out.write("            }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <div id=\"clouds\">\r\n");
      out.write("            <div class=\"cloud x1\"></div>\r\n");
      out.write("            <div class=\"cloud x1_5\"></div>\r\n");
      out.write("            <div class=\"cloud x2\"></div>\r\n");
      out.write("            <div class=\"cloud x3\"></div>\r\n");
      out.write("            <div class=\"cloud x4\"></div>\r\n");
      out.write("            <div class=\"cloud x5\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class='c'>\r\n");
      out.write("            <div class='_404'>404</div>\r\n");
      out.write("            <hr>\r\n");
      out.write("            <div class='_1'>THE PAGE</div>\r\n");
      out.write("            <div class='_2'>WAS NOT FOUND</div>\r\n");
      out.write("            <a class='btn' href='#'>BACK TO MARS</a>\r\n");
      out.write("        </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
